#!/bin/sh
# Harbor's hook launcher for the Cursor plugin (harborloop 0.5.11).
# Generated by harborloop's build-plugins script; do not edit by hand.
#
# Every hook in hooks.json runs `sh run.sh <hook>`. It:
#   1. does nothing on a machine where `harbor init` registered Harbor's hooks
#      in ~/.cursor/hooks.json or ~/.claude/settings.json itself, so no hook runs twice;
#   2. runs the hook that /harbor:login installed in ~/.harbor/bin, with this
#      hook's stdin;
#   3. before that sign-in, says at the start of a session how to connect.
# Its own paths all exit 0. The hook's exit code passes through, because a
# guardrail blocks a command by it.

hook=${1:-}

case "$hook" in
  session-context | session-report | session-capture | session-toolcontext | session-compact) ;;
  *) exit 0 ;;
esac

if grep -qs 'session-context\.mjs' "$HOME/.cursor/hooks.json" "$HOME/.claude/settings.json"; then
  exit 0
fi

dir=${HARBOR_HOME:-${ALEF0_HOME:-$HOME/.harbor}}
bin="$dir/bin/$hook.mjs"
if [ -x "$bin" ]; then
  exec "$bin"
fi

if [ "$hook" = session-context ] && [ ! -x "$dir/bin/session-context.mjs" ] &&
  grep -q '"hook_event_name"[[:space:]]*:[[:space:]]*"sessionStart"'; then
  echo '{"additional_context":"Harbor, a plugin in this Cursor, says: \"Harbor is installed but not connected. Run /harbor:login to sign in. No Harbor account yet? Join the waitlist at https://app.gethrbr.com/waitlist\" Mention this to the user once, briefly. Do not run the sign-in yourself."}'
fi
exit 0
