#!/bin/sh
# Harbor's hook launcher for the Claude Code plugin (harborloop 0.5.13).
# Generated by harborloop's build-plugins script; do not edit by hand.
#
# Every hook in hooks.json runs `sh run.sh <hook>`. It:
#   1. does nothing on a machine where `harbor init` registered Harbor's hooks
#      in ~/.claude/settings.json itself, so no hook runs twice;
#   2. runs the hook that /harbor:login installed in ~/.harbor/bin, with this
#      hook's stdin;
#   3. before that sign-in, says at the start of a session how to connect.
# Its own paths all exit 0. The hook's exit code passes through, because a
# guardrail blocks a command by it.

hook=${1:-}

case "$hook" in
  session-context | session-report | session-capture | session-toolcontext | session-compact) ;;
  *) exit 0 ;;
esac

# Inside Cursor, which runs Claude Code plugins' hooks too, Harbor's Cursor
# plugin is the one that runs (plan D12).
if [ -n "${CURSOR_PLUGIN_ROOT:-}" ]; then
  exit 0
fi

if grep -qs 'session-context\.mjs' "$HOME/.claude/settings.json"; then
  exit 0
fi

dir=${HARBOR_HOME:-${ALEF0_HOME:-$HOME/.harbor}}
bin="$dir/bin/$hook.mjs"
if [ -x "$bin" ]; then
  exec "$bin"
fi

if [ "$hook" = session-compact ] && [ ! -x "$dir/bin/session-context.mjs" ]; then
  echo '{"systemMessage":"Harbor is installed but not connected. Run /harbor:login to sign in. No Harbor account yet? Join the waitlist at https://app.gethrbr.com/waitlist"}'
fi
exit 0
