#!/bin/sh
# Runs harborloop 0.5.12, the Harbor CLI this plugin was built with.
# Generated by harborloop's build-plugins script; do not edit by hand.
here=$(pwd)
cd / || exit 1
exec npx -y "harborloop@0.5.12" "$@" --cwd "$here"
